kind = "DojoContract"
class_hash = "0x249892f8345fdba4eb16593c6a45f9de080d870964ca4b35b134fe3d07f53f3"
original_class_hash = "0x249892f8345fdba4eb16593c6a45f9de080d870964ca4b35b134fe3d07f53f3"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
