kind = "DojoContract"
class_hash = "0x66563413fe626826203be88aebda91bbce2c87476929d9f92b376cee789730d"
original_class_hash = "0x66563413fe626826203be88aebda91bbce2c87476929d9f92b376cee789730d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
