kind = "DojoContract"
class_hash = "0x74bc677c8e9949ff0166f31284e51a89ae0a5e38414f32888809f2a6846ff8a"
original_class_hash = "0x74bc677c8e9949ff0166f31284e51a89ae0a5e38414f32888809f2a6846ff8a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
