kind = "DojoModel"
class_hash = "0x580b432037b0253af19af0e610427da252994f972a15de3c39a4a2280b98158"
original_class_hash = "0x580b432037b0253af19af0e610427da252994f972a15de3c39a4a2280b98158"
abi = "manifests/dev/abis/base/models/dojo_starter_models_board_board.json"
name = "dojo_starter::models::board::board"

[[members]]
name = "id"
type = "u64"
key = true

[[members]]
name = "white_player"
type = "ContractAddress"
key = false

[[members]]
name = "black_player"
type = "ContractAddress"
key = false

[[members]]
name = "turn"
type = "bool"
key = false

[[members]]
name = "is_started"
type = "bool"
key = false

[[members]]
name = "is_finished"
type = "bool"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false
