kind = "DojoModel"
class_hash = "0x113c0ab02de1d4dfd5efd2dc20c70e6eb9cb2e602d81451ebcb1b3685a50ee1"
original_class_hash = "0x113c0ab02de1d4dfd5efd2dc20c70e6eb9cb2e602d81451ebcb1b3685a50ee1"
abi = "manifests/dev/abis/base/models/dojo_starter_models_board_cell.json"
name = "dojo_starter::models::board::cell"

[[members]]
name = "fenPos"
type = "u64"
key = true

[[members]]
name = "value"
type = "Type"
key = false
